stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind

  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t guilhermemarques1/fullapp-cicd:1.0 app/.
    - docker build -t guilhermemarques1/mysql-cicd:1.0 db/.
    - docker push guilhermemarques1/fullapp-cicd:1.0
    - docker push guilhermemarques1/mysql-cicd:1.0


deploy_gcp:
  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY

  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -rf ./fullapp-cicd/ && sudo git clone https://gitlab.com/GuilhermeMarques1/fullapp-cicd.git && cd fullapp-cicd && sudo chmod +x ./script.sh && ./script.sh"
